const data = {
    products: [
      {
        _id: '1',
        name: 'Steel Casing',
        category: 'Casing',
        image: '/images/casing.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '/images/fan.jpg',
        price: 100,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: '/images/motherboard.jpg',
        price: 220,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/ram.jpg',
        price: 78,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Pendrive',
        category: 'Pendrive',
        image: '/images/pendrive.jpeg',
        price: 65,
        brand: 'hp',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      
      
      {
        _id: '6',
        name: 'AMD Processor',
        category: 'Processor',
        image: '/images/processor.jpg',
        price: 139,
        brand: 'AMD',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'intel Processor',
        category: 'Processor',
        image: '/images/processor1.jpg',
        price: 139,
        brand: 'intel',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;