const data = {
    products: [
      {
        _id: '1',
        name: 'Steel Casing',
        category: 'Casing',
        image: '/images/casing.jpg',
        price: 120,
        countInStock: 5,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Thermaltech CPU Cooler',
        category: 'Shirts',
        image: '/images/fan.jpg',
        price: 100,
        countInStock: 5,
        brand: 'Thermaltech',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: '/images/motherboard.jpg',
        price: 220,
        countInStock: 5,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/ram.jpg',
        price: 78,
        countInStock: 5,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Pendrive',
        category: 'Pendrive',
        image: '/images/pendrive.jpeg',
        price: 65,
        countInStock: 5,
        brand: 'hp',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      
      
      {
        _id: '6',
        name: 'AMD Processor',
        category: 'Processor',
        image: '/images/processor.jpg',
        price: 139,
        countInStock: 5,
        brand: 'AMD',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      
      {
        _id: '7',
        name: 'Gigabyte AORUS 8GB 3200MHz RGB RAM',
        category: 'Desktop RAM',
        image: '/images/ramgigabyte.jpg',
        price: 4400,
        countInStock: 5,
        brand: 'Gigabyte',
        rating: 4.5,
        numReviews: 15,
        description: 'Model - Gigabyte Aorus RGB Capacity(MB) - 8GB Type - DDR4',
      },
      {
        _id: '8',
        name: 'intel Processor',
        category: 'Processor',
        image: '/images/processor1.jpg',
        price: 139,
        countInStock: 5,
        brand: 'intel',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;